feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    tmdb:
      apiKey:
      url: https://api.themoviedb.org/3
      language: en-US
